# Generated by Django 4.1.3 on 2022-11-18 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.PositiveIntegerField()),
                ("joindate", models.DateField(auto_now_add=True)),
                ("phone_no", models.CharField(blank=True, max_length=50)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.CharField(max_length=10)),
                ("phone_no", models.CharField(blank=True, max_length=50)),
                ("address", models.CharField(blank=True, max_length=200)),
                (
                    "faculty",
                    models.CharField(
                        choices=[
                            ("BSc. CSIT", "BSc. CSIT"),
                            ("BIT", "BIT"),
                            ("BSc.", "BSc."),
                            ("MSc.", "MSc."),
                        ],
                        default="Bsc. CSIT",
                        max_length=10,
                    ),
                ),
                ("fee", models.PositiveIntegerField(blank=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
