# Generated by Django 4.1.3 on 2022-11-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("by", models.CharField(default="college", max_length=20, null=True)),
                ("message", models.CharField(max_length=600)),
            ],
        ),
    ]
