# Generated by Django 4.1.3 on 2022-11-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0002_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="topic",
            field=models.CharField(default=False, max_length=100),
        ),
    ]
