# Generated by Django 4.1.3 on 2022-11-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0004_alter_notice_by_alter_notice_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty", models.CharField(max_length=10)),
                ("roll", models.CharField(blank=True, max_length=10)),
                ("present", models.CharField(max_length=10)),
                ("date", models.DateField()),
            ],
        ),
    ]
