# Generated by Django 4.1.3 on 2022-11-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0005_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("by", models.CharField(blank=True, default="college", max_length=20)),
                ("topic", models.CharField(blank=True, max_length=100)),
                ("message", models.CharField(max_length=600)),
            ],
        ),
    ]
