# Generated by Django 4.1.3 on 2022-11-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0007_leave"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
