# Generated by Django 4.1.3 on 2022-11-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0008_student_photo_teacher_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, upload_to="images/users/"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(blank=True, upload_to="images/users/"),
        ),
    ]
