# Generated by Django 4.1.3 on 2022-11-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0009_alter_student_photo_alter_teacher_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, upload_to="uploads"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(blank=True, upload_to="uploads"),
        ),
    ]
