# Generated by Django 4.1.3 on 2022-11-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0010_alter_student_photo_alter_teacher_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="photo",
        ),
    ]
